"""Generate a discrete-obstacle Gazebo world sized for dog3 (~0.30 m standing height)."""
import math, random

OUT = "/home/you/dog3_sim2sim/simulation/gazebo_bridge/worlds/obstacle_field.world"

GREY = "<ambient>0.55 0.55 0.58 1</ambient><diffuse>0.68 0.68 0.72 1</diffuse>"
WOOD = "<ambient>0.45 0.30 0.15 1</ambient><diffuse>0.60 0.40 0.20 1</diffuse>"
BLUE = "<ambient>0.20 0.35 0.55 1</ambient><diffuse>0.30 0.50 0.75 1</diffuse>"
RED = "<ambient>0.55 0.20 0.15 1</ambient><diffuse>0.75 0.30 0.22 1</diffuse>"

models = []


def box(name, size, pose, material=GREY):
    x, y, z, r, p, yalloc = pose
    models.append(f"""    <model name="{name}">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{size[0]} {size[1]} {size[2]}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{size[0]} {size[1]} {size[2]}</size></box></geometry>
          <material>{material}</material>
        </visual>
      </link>
      <pose>{x:.4f} {y:.4f} {z:.4f} {r:.4f} {p:.4f} {yalloc:.4f}</pose>
    </model>""")


# ---- +X : staircase, 5 steps x 0.035 m rise, 0.22 m tread, 0.9 m wide ----
RISE, TREAD, WIDTH = 0.035, 0.22, 0.9
X0 = 1.10
for i in range(5):
    h = (i + 1) * RISE
    box(f"stair_{i}", (TREAD, WIDTH, h),
        (X0 + (i + 0.5) * TREAD, 0.0, h / 2.0, 0, 0, 0), GREY)

# ---- -X : ramp rising away from the origin, 0.12 m over 0.9 m (~7.6 deg) ----
LEN, THICK, RISE_R = 0.90, 0.06, 0.12
pitch = math.atan2(RISE_R, LEN)
xc = -1.05
box("ramp", (LEN, 0.9, THICK),
    (xc, 0.0, (LEN / 2) * math.sin(pitch) + (THICK / 2) * math.cos(pitch), 0.0, pitch, 0.0), BLUE)
# landing pad at the top of the ramp
box("ramp_top", (0.45, 0.9, RISE_R),
    (xc - LEN / 2 - 0.225, 0.0, RISE_R / 2, 0, 0, 0), BLUE)

# ---- +Y : platform to step up onto (0.08 m) ----
box("platform_lo", (0.55, 0.30, 0.040), (0.0, 1.05, 0.020, 0, 0, 0), WOOD)
box("platform_hi", (0.55, 0.55, 0.080), (0.0, 1.53, 0.040, 0, 0, 0), WOOD)

# ---- -Y : step-over beam + rubble band ----
box("beam", (0.10, 1.20, 0.030), (0.0, -1.10, 0.015, 0, 0, 0), RED)
box("beam2", (0.10, 1.20, 0.055), (0.0, -1.45, 0.0275, 0, 0, 0), RED)

# ---- scattered rubble over an annulus around the spawn ----
rng = random.Random(7)
for i in range(26):
    ang = rng.uniform(0, 2 * math.pi)
    rad = rng.uniform(1.5, 2.2)
    sx = rng.uniform(0.05, 0.13)
    sy = rng.uniform(0.05, 0.13)
    h = rng.uniform(0.030, 0.060)
    box(f"rubble_{i}", (sx, sy, h),
        (rad * math.cos(ang), rad * math.sin(ang), h / 2, 0, 0, rng.uniform(0, math.pi)), GREY)

world = f"""<?xml version="1.0" ?>
<!-- Discrete-obstacle test field for dog3 (~0.30 m standing height).
     Feature directions from the spawn point at the origin:
       +X stairs (5 x 0.035 m)   -X ramp (0.12 m / 7.6 deg) + landing
       +Y platform (0.08 m)      -Y step-over beams + rubble ring
     Generated by tools/gen_obstacle_world.py -->
<sdf version="1.6">
  <world name="default">
    <physics type="ode">
      <max_step_size>0.002</max_step_size>
      <real_time_update_rate>500</real_time_update_rate>
    </physics>
    <include>
      <uri>model://sun</uri>
    </include>
    <include>
      <uri>model://ground_plane</uri>
    </include>
    <!-- publish /gazebo/model_states so the robot base pose can be measured -->
    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>50.0</update_rate>
    </plugin>

{chr(10).join(models)}
  </world>
</sdf>
"""

with open(OUT, "w") as fh:
    fh.write(world)
print(f"wrote {OUT}  ({len(models)} obstacle models)")
